### ISSUE TITLE
'Header magic did not match' on rpm package

### ISSUE THREAD

**Issue by aanno** [jordansissel/ruby-arr-pm#13]
Cross post from https://github.com/jordansissel/fpm/issues/1786 as I now believe it's a ruby-arr-pm problem.

**Comment by jordansissel** [comment]
https://github.com/jordansissel/ruby-arr-pm/pull/12 resolved this already, but I haven't put out a new release yet.

**Comment by jordansissel** [comment]
arr-pm v0.0.11 released. Thanks for reminding me ;)
